### ISSUE TITLE
Search Menu does not display anything

### ISSUE THREAD

**Issue by jbekesi** [programmfabrik/easydb-custom-data-type-iconclass#2]
When searching the Iconclass tree ("Baumansicht"), nothing is displayed at all.

      Plugin build info:
      
      Rev: c13b6368efaa2460aa86c7b2616b7f87cbabcb8b
      Repository: easydb-custom-data-type-iconclass
      Last change: 22.08.2022 19:29
      Build date: 09.09.2022 12:28

Easydb5 Version 106.0 and 105 before that.

Cf. screenshot:

![Bildschirmfoto 2022-09-27 um 11 42 03](https://user-images.githubusercontent.com/308033/192492706-9230f76a-7ec2-41c6-afcf-3fbdc48860d6.png)

**Comment by jbekesi** [comment]
**Fixed this:**

Line 62 of `CustomDataTypeIconClassTreeView.coffee`:

instead of `for iconclassEntry, key in data` use `for iconclassEntry, key in data.result`

and line 143 (or thereabouts):

instead of ` for iconclassEntry, key in data` use ` for iconclassEntry, key in data.result`

**Comment by jbekesi** [comment]
[iconclass_issue2.diff.gz](https://github.com/programmfabrik/easydb-custom-data-type-iconclass/files/9962694/iconclass_issue2.diff.gz) is the diff to apply (less hassle than a fork).

**Comment by StiftungAusNachlass** [comment]
Sorry for the late response - i did not get any notification for this issue.. Should be fixed in a latest Version. The iconclass-API changed.
